# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.mapper.article_mapper:
        class: AppBundle\Mapper\ArticleMapper
        arguments: ["@doctrine.dbal.default_connection"]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
